apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-workflows
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.45.11
    helm:
      releaseName: argo-workflows
      values: |
        workflow:
          serviceAccount:
            create: true
        controller:
          workflowNamespaces:
            - argo-workflows
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        server:
          extraArgs:
            - --auth-mode=server
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 512Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
