apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: homepage
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: homepage
      repoURL: https://jameswynn.github.io/helm-charts
      helm:
        valueFiles:
          - $values-repo/homepage/values.yaml
    - repoURL: https://github.com/mogrizovic/gitops-k8s
      targetRevision: HEAD
      ref: values-repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
