apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx 
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.0
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          admissionWebhooks:
            enabled: false
          resources:
            limits:
              cpu: 100m
              memory: 90Mi
            requests:
              cpu: 200m
              memory: 512Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
