apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.17.2
    helm:
      releaseName: sealed-secrets-controller
      values: |
        fullnameOverride: sealed-secrets-controller
        resources:
          limits:
            cpu: 10m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 128Mi 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true

