apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-boot-example-preview
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: mogrizovic
        # The Github repository
        repo: spring-boot-example
        # # Reference to a Secret containing an access token. (optional)
        # tokenRef:
        #   secretName: github-token
        #   key: token
        # # (optional) use a GitHub App to access the API instead of a PAT.
        # appSecretName: github-app-repo-creds
        # Labels is used to filter the PRs that you want to target. (optional)
        labels:
        - preview
      requeueAfterSeconds: 1800
  template:
    metadata:
      name: 'spring-boot-example-{{.branch | replace "/" "_"}}-{{.number}}'
    spec:
      source:
        repoURL: 'https://github.com/mogrizovic/spring-boot-example.git'
        targetRevision: '{{.head_sha}}'
        path: k8s/
        helm:
          valueFiles:
            - values.yaml
            - envs/preview/values.yaml
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: apps-preview
