apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: receivers
  namespace: monitoring
  labels:
    alertmanagerConfig: receivers
spec:
  route:
    receiver: discord_webhook
  receivers:
  - name: discord_webhook
    discordConfigs:
    - sendResolved: true
      apiURL: 
        name: alertmanager-kube-prometheus-stack-alertmanager-alert-destinations
        key: discord_webhook

