crds:
  enabled: false
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - prometheus.k3s.home
    paths:
      - /
    pathType: Prefix
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    alertmanagerConfigSelector:
      matchLabels:
        alertmanagerConfig: receivers
    secrets:
      - alertmanager-kube-prometheus-stack-alertmanager-alert-destinations
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - alertmanager.k3s.home
    paths:
      - /
    pathType: Prefix
  secrets:
    - kube-prometheus-stack-alert-destinations
grafana:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - grafana.k3s.home
    path: /
