crds:
  enabled: false
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - prometheus.k3s.home
    paths:
      - /
    pathType: Prefix
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    alertmanagerConfigSelector:
      matchLabels:
        alertmanagerConfig: receivers
    secrets:
      - alertmanager-alert-destinations
  config:
    global:
      resolve_timeout: 6m
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
      - target_matchers:
          - 'alertname = InfoInhibitor'
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - receiver: 'discord_webhook'
        matchers:
          - alertname = "Watchdog"
    receivers:
    - name: "null"
    - name: discord_webhook
    templates:
    - '/etc/alertmanager/config/*.tmpl'
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - alertmanager.k3s.home
    paths:
      - /
    pathType: Prefix
  secrets:
    - kube-prometheus-stack-alert-destinations
grafana:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - grafana.k3s.home
    path: /
