---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: guestbook-secret-store
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      # azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      tenantId: "9deea610-7f6c-4a29-9e62-0c8cc9b93ea1"
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "https://guestbook-vault.vault.azure.net/"
      authSecretRef:
        # points to the secret that contains
        # the azure service principal credentials
        clientId:
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: guestbook-external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: guestbook-secret-store

  target:
    name: test-secret
    creationPolicy: Owner

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: test-secret-key
    remoteRef:
      key: test
