apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: gh-pr-dynamic-workflow-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-hook
      eventSourceName: github
      eventName: gh-hook
      filters:
        data:
          - path: headers.X-Github-Event
            type: string
            value:
              - pull_request
          - path: body.action
            type: string
            value:
              - opened
              - edited
              - reopened
              - synchronize
          - path: body.pull_request.state
            type: string
            value:
              - open
          - path: body.pull_request.base.ref
            type: string
            value:
              - master
          - path: body.sender.login
            type: string
            comparator: "!="
            value: 
              - "myargoworkflows"
  triggers:
    - template:
        name: dynamic-pr-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: pr-
              spec:
                # ttlStrategy:
                #   secondsAfterCompletion: 300 # to cleanup pods after ttl
                workflowTemplateRef:
                  name: "wf-tmpl-"  # this name depends on what repo initiated the webhook
                  clusterScope: true
                arguments:
                  parameters:
                    - name: repo_name
                      value: ""
                    - name: commit_message
                      value: ""
                    - name: image_variant
                      value: ""
                    - name: branch_name
                      value: ""
                    - name: commit_sha
                      value: ""
                    - name: environment
                      value: "preview"
          parameters:
            - src:
                dependencyName: github-hook
                dataKey: body.pull_request.head.repo.name
              dest: spec.workflowTemplateRef.name
              operation: append
            - src:
                dependencyName: github-hook
                dataKey: body.pull_request.head.repo.full_name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: github-hook
                dataTemplate: '{{ .Input.body.pull_request.head.ref | replace "/" "_" }}'
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: github-hook
                dataKey: body.pull_request.head.ref
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: github-hook
                dataTemplate: "{{ .Input.body.pull_request.head.sha | substr 0 7 }}"
              dest: spec.arguments.parameters.4.value
            - src:
                dependencyName: github-hook
                dataTemplate: "{{ .Input.body.pull_request.head.repo.name }}-{{ .Input.body.pull_request.number }}-{{ .Input.body.pull_request.head.sha | substr 0 7 }}"
              dest: metadata.name
              operation: append

