apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github
  namespace: argo-workflows
spec:
  ingressClassName: nginx
  rules:
  - host: "*.share.zrok.io"
    http:
      paths:
      - backend:
          service:
            name: github-eventsource-svc
            port:
              number: 12000
        path: /push
        pathType: Prefix

